-- MySQL Script generated by MySQL Workbench
-- Tuesday 25 October 2016 11:47:06 AM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema returns
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema returns
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `returns` DEFAULT CHARACTER SET latin1 ;
USE `returns` ;

-- -----------------------------------------------------
-- Table `returns`.`admin_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`admin_group` ;

CREATE TABLE IF NOT EXISTS `returns`.`admin_group` (
  `groupid` TINYINT(4) NOT NULL,
  `groupname` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`groupid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`auth_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`auth_group` ;

CREATE TABLE IF NOT EXISTS `returns`.`auth_group` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`django_content_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`django_content_type` ;

CREATE TABLE IF NOT EXISTS `returns`.`django_content_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `app_label` VARCHAR(100) NOT NULL,
  `model` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `django_content_type_app_label_76bd3d3b_uniq` (`app_label` ASC, `model` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 184
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`auth_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`auth_permission` ;

CREATE TABLE IF NOT EXISTS `returns`.`auth_permission` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `content_type_id` INT(11) NOT NULL,
  `codename` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_permission_content_type_id_01ab375a_uniq` (`content_type_id` ASC, `codename` ASC),
  CONSTRAINT `auth_permissi_content_type_id_2f476e4b_fk_django_content_type_id`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `returns`.`django_content_type` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 729
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`auth_group_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`auth_group_permissions` ;

CREATE TABLE IF NOT EXISTS `returns`.`auth_group_permissions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `group_id` INT(11) NOT NULL,
  `permission_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_group_permissions_group_id_0cd325b0_uniq` (`group_id` ASC, `permission_id` ASC),
  INDEX `auth_group_permissi_permission_id_84c5c92e_fk_auth_permission_id` (`permission_id` ASC),
  CONSTRAINT `auth_group_permissions_group_id_b120cbf9_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `returns`.`auth_group` (`id`),
  CONSTRAINT `auth_group_permissi_permission_id_84c5c92e_fk_auth_permission_id`
    FOREIGN KEY (`permission_id`)
    REFERENCES `returns`.`auth_permission` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 854
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`auth_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`auth_user` ;

CREATE TABLE IF NOT EXISTS `returns`.`auth_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(128) NOT NULL,
  `last_login` DATETIME NULL DEFAULT NULL,
  `is_superuser` TINYINT(1) NOT NULL,
  `username` VARCHAR(150) NOT NULL,
  `first_name` VARCHAR(30) NOT NULL,
  `last_name` VARCHAR(30) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `is_staff` TINYINT(1) NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  `date_joined` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 511
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`auth_user_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`auth_user_groups` ;

CREATE TABLE IF NOT EXISTS `returns`.`auth_user_groups` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `group_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_user_groups_user_id_94350c0c_uniq` (`user_id` ASC, `group_id` ASC),
  INDEX `auth_user_groups_group_id_97559544_fk_auth_group_id` (`group_id` ASC),
  CONSTRAINT `auth_user_groups_group_id_97559544_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `returns`.`auth_group` (`id`),
  CONSTRAINT `auth_user_groups_user_id_6a12ed8b_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `returns`.`auth_user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 252
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`auth_user_user_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`auth_user_user_permissions` ;

CREATE TABLE IF NOT EXISTS `returns`.`auth_user_user_permissions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `permission_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_user_user_permissions_user_id_14a6b632_uniq` (`user_id` ASC, `permission_id` ASC),
  INDEX `auth_user_user_perm_permission_id_1fbb5f2c_fk_auth_permission_id` (`permission_id` ASC),
  CONSTRAINT `auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `returns`.`auth_user` (`id`),
  CONSTRAINT `auth_user_user_perm_permission_id_1fbb5f2c_fk_auth_permission_id`
    FOREIGN KEY (`permission_id`)
    REFERENCES `returns`.`auth_permission` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3203
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`business_model`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`business_model` ;

CREATE TABLE IF NOT EXISTS `returns`.`business_model` (
  `modelid` TINYINT(4) NOT NULL AUTO_INCREMENT,
  `model_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`modelid`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`catalog_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`catalog_category` ;

CREATE TABLE IF NOT EXISTS `returns`.`catalog_category` (
  `category_id` INT(11) NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NULL DEFAULT NULL,
  `status` TINYINT(2) NULL DEFAULT '0',
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 94
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`catalog_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`catalog_product` ;

CREATE TABLE IF NOT EXISTS `returns`.`catalog_product` (
  `product_id` INT(11) NOT NULL AUTO_INCREMENT,
  `product_name` TEXT NULL DEFAULT NULL,
  `ean` VARCHAR(45) NULL DEFAULT NULL COMMENT '	',
  `upc` VARCHAR(45) NULL DEFAULT NULL,
  `asin` VARCHAR(45) NULL DEFAULT NULL,
  `isbn` VARCHAR(45) NULL DEFAULT NULL,
  `brand` VARCHAR(45) NULL DEFAULT NULL,
  `meta` TEXT NULL DEFAULT NULL,
  `category_id` INT(11) NOT NULL,
  `color` VARCHAR(30) NULL DEFAULT NULL,
  `model` VARCHAR(45) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `part_number` VARCHAR(45) NULL DEFAULT NULL,
  `source_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`, `category_id`),
  INDEX `fk_catalog_product_catalog_category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_catalog_product_catalog_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `returns`.`catalog_category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2799
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`client_bank_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`client_bank_details` ;

CREATE TABLE IF NOT EXISTS `returns`.`client_bank_details` (
  `bd_id` INT(11) NOT NULL AUTO_INCREMENT,
  `client_id` INT(11) NULL DEFAULT NULL,
  `bank_name` VARCHAR(45) NULL DEFAULT NULL,
  `ifsc_code` VARCHAR(45) NULL DEFAULT NULL,
  `account_number` VARCHAR(45) NULL DEFAULT NULL,
  `name_on_account` VARCHAR(45) NULL DEFAULT NULL,
  `created_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_updated_date` DATETIME NOT NULL,
  `last_updated_by` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`bd_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 84
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`client_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`client_details` ;

CREATE TABLE IF NOT EXISTS `returns`.`client_details` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `regi_name` VARCHAR(150) NOT NULL,
  `act_manager` VARCHAR(255) NOT NULL,
  `con_email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(30) NOT NULL,
  `VAT` VARCHAR(15) NOT NULL,
  `address` TEXT NOT NULL,
  `type` VARCHAR(15) NOT NULL,
  `marketplace` TINYINT(1) NOT NULL DEFAULT '0',
  `can_invoice` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 101
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `returns`.`client_entity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`client_entity` ;

CREATE TABLE IF NOT EXISTS `returns`.`client_entity` (
  `client_entity_id` TINYINT(4) NOT NULL,
  `client_entity_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`client_entity_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`client_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`client_group` ;

CREATE TABLE IF NOT EXISTS `returns`.`client_group` (
  `groupid` TINYINT(4) NOT NULL,
  `groupname` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`groupid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`client_product_upload`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`client_product_upload` ;

CREATE TABLE IF NOT EXISTS `returns`.`client_product_upload` (
  `cpu_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '	',
  `product_name` VARCHAR(255) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `client_sku` VARCHAR(45) NULL DEFAULT NULL,
  `client_identifier` VARCHAR(45) NULL DEFAULT NULL,
  `quantity` INT(11) NULL DEFAULT NULL,
  `user_id` INT(11) NOT NULL,
  `product_id` INT(11) NULL DEFAULT '0',
  `wh_id` INT(11) NOT NULL,
  `rms_bulk_cache` VARCHAR(50) NULL DEFAULT NULL,
  `pickup_requested` INT(2) NULL DEFAULT '0',
  `color` VARCHAR(20) NULL DEFAULT NULL,
  `category_id` INT(11) NULL DEFAULT NULL,
  `manufacturer` VARCHAR(255) NULL DEFAULT NULL,
  `meta` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`cpu_id`, `user_id`, `wh_id`),
  INDEX `client_sku` (`client_sku` ASC, `client_identifier` ASC),
  INDEX `fk_client_product_upload_1_idx` (`user_id` ASC),
  INDEX `fk_client_product_upload_2_idx` (`product_id` ASC),
  INDEX `fk_client_product_upload_3_idx` (`category_id` ASC),
  CONSTRAINT `fk_client_product_upload_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `returns`.`auth_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_product_upload_2`
    FOREIGN KEY (`product_id`)
    REFERENCES `returns`.`catalog_product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_product_upload_3`
    FOREIGN KEY (`category_id`)
    REFERENCES `returns`.`catalog_category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 574
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`tax_states`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`tax_states` ;

CREATE TABLE IF NOT EXISTS `returns`.`tax_states` (
  `id` TINYINT(4) NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `country` VARCHAR(255) NULL DEFAULT NULL,
  `status` TINYINT(4) NULL DEFAULT '1',
  `created_date` DATETIME NULL DEFAULT NULL,
  `updated_date` DATETIME NULL DEFAULT NULL,
  `updated_by` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `returns`.`warehouse_master`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`warehouse_master` ;

CREATE TABLE IF NOT EXISTS `returns`.`warehouse_master` (
  `wh_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `plot_number` VARCHAR(50) NOT NULL DEFAULT '',
  `address1` VARCHAR(255) NOT NULL DEFAULT '',
  `address2` VARCHAR(255) NULL DEFAULT NULL,
  `landmark` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(150) NOT NULL DEFAULT '',
  `state_id` TINYINT(4) NOT NULL,
  `pincode` VARCHAR(20) NOT NULL DEFAULT '',
  `warehouse_code` VARCHAR(45) NULL DEFAULT NULL,
  `status` TINYINT(2) NOT NULL DEFAULT '0',
  PRIMARY KEY (`wh_id`),
  INDEX `fk_warehouse_master_1_idx` (`state_id` ASC),
  CONSTRAINT `fk_warehouse_master_1`
    FOREIGN KEY (`state_id`)
    REFERENCES `returns`.`tax_states` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 212
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`user_client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`user_client` ;

CREATE TABLE IF NOT EXISTS `returns`.`user_client` (
  `user_id` INT(11) NOT NULL,
  `client_name` VARCHAR(150) NOT NULL DEFAULT '',
  `business_name` VARCHAR(255) NOT NULL DEFAULT '',
  `act_manager` VARCHAR(255) NOT NULL DEFAULT '',
  `contact_email` VARCHAR(255) NOT NULL DEFAULT '',
  `contact_phone` VARCHAR(30) NOT NULL DEFAULT '',
  `address1` VARCHAR(255) NOT NULL DEFAULT '',
  `address2` VARCHAR(255) NULL DEFAULT '',
  `landmark` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(150) NOT NULL DEFAULT '',
  `state_id` TINYINT(4) NOT NULL,
  `pincode` VARCHAR(20) NOT NULL DEFAULT '',
  `marketplace` TINYINT(1) NOT NULL DEFAULT '0',
  `can_invoice` TINYINT(1) NOT NULL DEFAULT '0',
  `pan_number` VARCHAR(20) NOT NULL DEFAULT '',
  `vat_number` VARCHAR(50) NOT NULL DEFAULT '',
  `status` TINYINT(2) NOT NULL DEFAULT '0',
  `overboxd_client_id` INT(5) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  INDEX `fk_client_1_idx` (`user_id` ASC),
  INDEX `user_id` (`user_id` ASC, `contact_email` ASC, `contact_phone` ASC, `address1` ASC),
  INDEX `fk_user_client_2_idx` (`state_id` ASC),
  CONSTRAINT `fk_user_client_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `returns`.`auth_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_client_2`
    FOREIGN KEY (`state_id`)
    REFERENCES `returns`.`tax_states` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`warehouse_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`warehouse_status` ;

CREATE TABLE IF NOT EXISTS `returns`.`warehouse_status` (
  `status_id` TINYINT(2) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `value` VARCHAR(45) NULL DEFAULT NULL,
  `display_order` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`status_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`client_warehouse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`client_warehouse` ;

CREATE TABLE IF NOT EXISTS `returns`.`client_warehouse` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `wh_id` INT(11) NOT NULL,
  `client_id` INT(11) NOT NULL,
  `tin_number` VARCHAR(45) NOT NULL DEFAULT '',
  `poc_name` VARCHAR(255) NULL DEFAULT NULL,
  `poc_contact` VARCHAR(30) NULL DEFAULT NULL,
  `status` TINYINT(2) NULL DEFAULT NULL,
  `poc_landline` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `wh_id` (`wh_id` ASC, `client_id` ASC),
  INDEX `fk_client_warehouse_1_idx` (`client_id` ASC),
  INDEX `fk_client_warehouse_2_idx` (`wh_id` ASC),
  INDEX `fk_client_warehouse_3_idx` (`status` ASC),
  CONSTRAINT `fk_client_warehouse_1`
    FOREIGN KEY (`wh_id`)
    REFERENCES `returns`.`warehouse_master` (`wh_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_warehouse_2`
    FOREIGN KEY (`client_id`)
    REFERENCES `returns`.`user_client` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_warehouse_3`
    FOREIGN KEY (`status`)
    REFERENCES `returns`.`warehouse_status` (`status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 62
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`color_master`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`color_master` ;

CREATE TABLE IF NOT EXISTS `returns`.`color_master` (
  `color_id` INT(11) NOT NULL AUTO_INCREMENT,
  `color_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`color_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 66
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`customer_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`customer_group` ;

CREATE TABLE IF NOT EXISTS `returns`.`customer_group` (
  `groupid` TINYINT(4) NOT NULL,
  `groupname` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`groupid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`django_admin_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`django_admin_log` ;

CREATE TABLE IF NOT EXISTS `returns`.`django_admin_log` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `action_time` DATETIME NOT NULL,
  `object_id` LONGTEXT NULL DEFAULT NULL,
  `object_repr` VARCHAR(200) NOT NULL,
  `action_flag` SMALLINT(5) UNSIGNED NOT NULL,
  `change_message` LONGTEXT NOT NULL,
  `content_type_id` INT(11) NULL DEFAULT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `django_admin__content_type_id_c4bce8eb_fk_django_content_type_id` (`content_type_id` ASC),
  INDEX `django_admin_log_user_id_c564eba6_fk_auth_user_id` (`user_id` ASC),
  CONSTRAINT `django_admin_log_user_id_c564eba6_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `returns`.`auth_user` (`id`),
  CONSTRAINT `django_admin__content_type_id_c4bce8eb_fk_django_content_type_id`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `returns`.`django_content_type` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 107
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `returns`.`django_migrations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`django_migrations` ;

CREATE TABLE IF NOT EXISTS `returns`.`django_migrations` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `app` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `applied` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`django_session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`django_session` ;

CREATE TABLE IF NOT EXISTS `returns`.`django_session` (
  `session_key` VARCHAR(40) NOT NULL,
  `session_data` LONGTEXT NOT NULL,
  `expire_date` DATETIME NOT NULL,
  PRIMARY KEY (`session_key`),
  INDEX `django_session_de54fa62` (`expire_date` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`po_payment_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`po_payment_type` ;

CREATE TABLE IF NOT EXISTS `returns`.`po_payment_type` (
  `payment_id` TINYINT(4) NOT NULL,
  `payment_name` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`payment_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`po_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`po_status` ;

CREATE TABLE IF NOT EXISTS `returns`.`po_status` (
  `po_status_id` TINYINT(3) UNSIGNED NOT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  `value` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`po_status_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`lot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`lot` ;

CREATE TABLE IF NOT EXISTS `returns`.`lot` (
  `lot_id` INT(11) NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `meta` TEXT NULL DEFAULT NULL,
  `initial_price` DECIMAL(10,2) NULL DEFAULT NULL,
  `client_id` INT(11) NULL DEFAULT NULL,
  `payment_mode` TINYINT(4) NULL DEFAULT NULL COMMENT 'pre 0 post 1',
  `po_approved` BIT(1) NULL DEFAULT b'0',
  `initial_qty` SMALLINT(6) NULL DEFAULT NULL,
  `accepted_qty` SMALLINT(6) NULL DEFAULT NULL,
  `accepted_price` DECIMAL(10,2) NULL DEFAULT NULL,
  `user_uid` INT(11) NOT NULL,
  `po_status_id` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
  `payment_type_id` TINYINT(4) UNSIGNED NULL DEFAULT NULL,
  `ean_attr` VARCHAR(50) NULL DEFAULT NULL,
  `op_center` INT(11) NULL DEFAULT NULL,
  `business_model` TINYINT(4) NULL DEFAULT NULL,
  `po_number` VARCHAR(45) NULL DEFAULT NULL,
  `utr` VARCHAR(50) NULL DEFAULT NULL,
  `file_hash_key` VARCHAR(100) NULL DEFAULT NULL,
  `price_updated` BIT(1) NULL DEFAULT NULL,
  `paid_date` DATE NULL DEFAULT NULL,
  `client_name` VARCHAR(45) NULL DEFAULT NULL,
  `op_center_name` VARCHAR(255) NULL DEFAULT NULL,
  `total_days` INT(5) NULL DEFAULT NULL,
  `pickup_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`lot_id`),
  INDEX `fk_po_upload_2` (`payment_type_id` ASC),
  INDEX `fk_uid_idx` (`user_uid` ASC),
  INDEX `fk_po_upload_1_idx` (`payment_mode` ASC),
  INDEX `fk_po_upload_1_idx1` (`client_id` ASC),
  INDEX `po_status_id` (`po_status_id` ASC),
  INDEX `fk_business_model_idx` (`business_model` ASC),
  CONSTRAINT `fk_business_model`
    FOREIGN KEY (`business_model`)
    REFERENCES `returns`.`business_model` (`modelid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payment_mode`
    FOREIGN KEY (`payment_mode`)
    REFERENCES `returns`.`po_payment_type` (`payment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_po_upload_3`
    FOREIGN KEY (`user_uid`)
    REFERENCES `returns`.`auth_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `lot_ibfk_1`
    FOREIGN KEY (`po_status_id`)
    REFERENCES `returns`.`po_status` (`po_status_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 571
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`lot_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`lot_details` ;

CREATE TABLE IF NOT EXISTS `returns`.`lot_details` (
  `lot_details_id` INT(11) NOT NULL AUTO_INCREMENT,
  `catalog_id` INT(11) NULL DEFAULT NULL COMMENT 'from catalog_tbl foreign',
  `qty` SMALLINT(6) NULL DEFAULT NULL,
  `base_tprice` DECIMAL(8,2) NULL DEFAULT NULL,
  `approval_status` TINYINT(2) NULL DEFAULT NULL,
  `approval_by` VARCHAR(50) NULL DEFAULT NULL,
  `approval_date` DATETIME NULL DEFAULT NULL,
  `total_tprice` DECIMAL(10,2) NULL DEFAULT NULL,
  `pickup_status` BIT(1) NULL DEFAULT NULL,
  `pickup_qty` INT(11) NULL DEFAULT NULL,
  `pickup_by` INT(11) NULL DEFAULT NULL,
  `pickup_date` DATETIME NULL DEFAULT NULL,
  `lot_id` INT(11) NOT NULL,
  `warranty_status` TINYINT(4) NULL DEFAULT NULL,
  `warranty_duration` VARCHAR(45) NULL DEFAULT NULL,
  `color` VARCHAR(45) NULL DEFAULT NULL,
  `model` VARCHAR(45) NULL DEFAULT NULL,
  `product_name` VARCHAR(45) NULL DEFAULT NULL,
  `ean` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`lot_details_id`),
  INDEX `fk_po_details_1_idx` (`catalog_id` ASC),
  INDEX `fk_lot_details_1_idx` (`lot_id` ASC),
  CONSTRAINT `fk_lot_details_1`
    FOREIGN KEY (`lot_id`)
    REFERENCES `returns`.`lot` (`lot_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_po_details_1`
    FOREIGN KEY (`catalog_id`)
    REFERENCES `returns`.`catalog_product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11915
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`manufacturer_master`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`manufacturer_master` ;

CREATE TABLE IF NOT EXISTS `returns`.`manufacturer_master` (
  `manufacturer_id` INT(11) NOT NULL AUTO_INCREMENT,
  `manufacturer_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`manufacturer_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 665
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`po_comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`po_comments` ;

CREATE TABLE IF NOT EXISTS `returns`.`po_comments` (
  `id` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `po_details_id` INT(11) NULL DEFAULT NULL,
  `comments` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_po_details_id` (`po_details_id` ASC),
  CONSTRAINT `fk_po_details_id`
    FOREIGN KEY (`po_details_id`)
    REFERENCES `returns`.`lot_details` (`lot_details_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`po_number`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`po_number` ;

CREATE TABLE IF NOT EXISTS `returns`.`po_number` (
  `poid` INT(11) NOT NULL,
  `filepath` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`poid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`po_payment_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`po_payment_info` ;

CREATE TABLE IF NOT EXISTS `returns`.`po_payment_info` (
  `payinfo_id` INT(11) NOT NULL AUTO_INCREMENT,
  `qty` SMALLINT(5) UNSIGNED NULL DEFAULT NULL,
  `amount_paid` DECIMAL(10,2) NULL DEFAULT '0.00',
  `payment_date` DATETIME NULL DEFAULT NULL,
  `payment_info` VARCHAR(45) NULL DEFAULT NULL,
  `lot_id` INT(11) NULL DEFAULT NULL,
  `utr` VARCHAR(45) NULL DEFAULT NULL,
  `bank_details_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`payinfo_id`),
  INDEX `fk_popaymentinfo_client_bank_details_idx` (`bank_details_id` ASC),
  INDEX `fk_po_payment_info_1_idx` (`lot_id` ASC),
  CONSTRAINT `fk_popaymentinfo_client_bank_details`
    FOREIGN KEY (`bank_details_id`)
    REFERENCES `returns`.`client_bank_details` (`bd_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_po_payment_info_1`
    FOREIGN KEY (`lot_id`)
    REFERENCES `returns`.`lot` (`lot_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 79
DEFAULT CHARACTER SET = utf8
COMMENT = 'for finance';


-- -----------------------------------------------------
-- Table `returns`.`po_request_overcart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`po_request_overcart` ;

CREATE TABLE IF NOT EXISTS `returns`.`po_request_overcart` (
  `overcart_request_id` INT(11) NOT NULL,
  `client_product_upload_cpu_id` INT(11) NOT NULL,
  `pickup_request_date` DATETIME NULL DEFAULT NULL,
  `pickup_schedule_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`overcart_request_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`role` ;

CREATE TABLE IF NOT EXISTS `returns`.`role` (
  `rid` TINYINT(4) NOT NULL,
  `rname` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`rid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`state_tax_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`state_tax_category` ;

CREATE TABLE IF NOT EXISTS `returns`.`state_tax_category` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `state_id` TINYINT(4) NULL DEFAULT NULL,
  `hardware_category` VARCHAR(255) CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `is_limit` INT(11) NULL DEFAULT '0',
  `category_id` INT(11) NULL DEFAULT NULL,
  `tax_percentage` FLOAT NULL DEFAULT NULL,
  `status` TINYINT(4) NULL DEFAULT NULL,
  `created_date` DATETIME NULL DEFAULT NULL,
  `updated_date` DATETIME NULL DEFAULT NULL,
  `updated_by` VARCHAR(45) CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `min_limit` DECIMAL(10,0) NULL DEFAULT NULL,
  `max_limit` DECIMAL(10,0) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_state_tax_category_1_idx` (`state_id` ASC),
  INDEX `fk_state_tax_category_2_idx` (`category_id` ASC),
  CONSTRAINT `fk_state_tax_category_1`
    FOREIGN KEY (`state_id`)
    REFERENCES `returns`.`tax_states` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 489
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`user_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`user_groups` ;

CREATE TABLE IF NOT EXISTS `returns`.`user_groups` (
  `gid` INT(11) NOT NULL AUTO_INCREMENT,
  `gname` VARCHAR(75) NOT NULL DEFAULT '',
  PRIMARY KEY (`gid`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`user` ;

CREATE TABLE IF NOT EXISTS `returns`.`user` (
  `uid` INT(11) NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL DEFAULT NULL,
  `lastname` VARCHAR(45) NULL DEFAULT NULL,
  `is_active` BIT(1) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `groups_gid` INT(11) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`uid`),
  INDEX `fk_group_gid_idx` (`groups_gid` ASC),
  CONSTRAINT `fk_group_gid`
    FOREIGN KEY (`groups_gid`)
    REFERENCES `returns`.`user_groups` (`gid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 324
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`user_admin_overcart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`user_admin_overcart` ;

CREATE TABLE IF NOT EXISTS `returns`.`user_admin_overcart` (
  `admin_id` INT(11) NOT NULL AUTO_INCREMENT,
  `group_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`admin_id`),
  CONSTRAINT `fk_overcart_admin_1`
    FOREIGN KEY (`admin_id`)
    REFERENCES `returns`.`user` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`user_customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`user_customer` ;

CREATE TABLE IF NOT EXISTS `returns`.`user_customer` (
  `user_uid` INT(11) NOT NULL,
  `group_id` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`user_uid`),
  INDEX `fk_customer_user1_idx` (`user_uid` ASC),
  CONSTRAINT `fk_customer_user1`
    FOREIGN KEY (`user_uid`)
    REFERENCES `returns`.`user` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`user_doc_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`user_doc_type` ;

CREATE TABLE IF NOT EXISTS `returns`.`user_doc_type` (
  `id` TINYINT(4) NOT NULL,
  `name` VARCHAR(45) NOT NULL DEFAULT '',
  `doc_key` VARCHAR(150) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `doc_key` (`doc_key` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`user_docs_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`user_docs_status` ;

CREATE TABLE IF NOT EXISTS `returns`.`user_docs_status` (
  `status_id` TINYINT(4) NOT NULL AUTO_INCREMENT,
  `status_name` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`status_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`user_docs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`user_docs` ;

CREATE TABLE IF NOT EXISTS `returns`.`user_docs` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `doc_key` TINYINT(4) NOT NULL,
  `doc_file` LONGBLOB NOT NULL,
  `doc_status` TINYINT(2) NOT NULL DEFAULT '0',
  `approved_by` INT(11) NULL DEFAULT NULL,
  `additional_comment` TEXT NULL DEFAULT NULL,
  `attachment` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `auth_user_id` (`user_id` ASC, `doc_key` ASC),
  INDEX `fk_user_docs_2_idx` (`approved_by` ASC),
  INDEX `fk_user_docs_3_idx` (`doc_status` ASC),
  INDEX `fk_user_docs_4_idx` (`doc_key` ASC),
  CONSTRAINT `fk_user_docs_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `returns`.`auth_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_docs_2`
    FOREIGN KEY (`approved_by`)
    REFERENCES `returns`.`auth_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_docs_3`
    FOREIGN KEY (`doc_status`)
    REFERENCES `returns`.`user_docs_status` (`status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_docs_4`
    FOREIGN KEY (`doc_key`)
    REFERENCES `returns`.`user_doc_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`user_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`user_permissions` ;

CREATE TABLE IF NOT EXISTS `returns`.`user_permissions` (
  `pid` INT(11) NOT NULL AUTO_INCREMENT,
  `pname` VARCHAR(100) NOT NULL DEFAULT '',
  PRIMARY KEY (`pid`),
  INDEX `pname` (`pname` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`user_group_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`user_group_permissions` ;

CREATE TABLE IF NOT EXISTS `returns`.`user_group_permissions` (
  `group_id` INT(11) NOT NULL,
  `pid` INT(11) NOT NULL,
  INDEX `fk_group_permission_2_idx` (`pid` ASC),
  INDEX `group_id` (`group_id` ASC),
  CONSTRAINT `fk_group_permission_2`
    FOREIGN KEY (`pid`)
    REFERENCES `returns`.`user_permissions` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_group_permissions_ibfk_1`
    FOREIGN KEY (`group_id`)
    REFERENCES `returns`.`user_groups` (`gid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`user_verification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`user_verification` ;

CREATE TABLE IF NOT EXISTS `returns`.`user_verification` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `verification_code` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `created_on` DATETIME NOT NULL,
  `is_used` TINYINT(4) NOT NULL DEFAULT '0',
  `used_on` DATETIME NULL DEFAULT NULL,
  `user_verificationcol` INT(11) NULL,
  PRIMARY KEY (`id`, `user_id`),
  UNIQUE INDEX `verification_code` (`verification_code` ASC),
  INDEX `fk_user_verification_1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_verification_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `returns`.`auth_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `returns`.`warehouse_shelf_code`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`warehouse_shelf_code` ;

CREATE TABLE IF NOT EXISTS `returns`.`warehouse_shelf_code` (
  `zone` VARCHAR(45) NOT NULL DEFAULT '',
  `location` VARCHAR(45) NOT NULL DEFAULT '',
  `wh_id` INT(11) NOT NULL,
  `client_id` INT(11) NOT NULL,
  PRIMARY KEY (`client_id`, `wh_id`, `location`, `zone`),
  INDEX `location` (`location` ASC, `zone` ASC),
  INDEX `fk_warehouse_shelf_code_1_idx` (`wh_id` ASC),
  INDEX `fk_warehouse_shelf_code_2_idx` (`client_id` ASC),
  CONSTRAINT `fk_warehouse_shelf_code_1`
    FOREIGN KEY (`wh_id`)
    REFERENCES `returns`.`warehouse_master` (`wh_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_warehouse_shelf_code_2`
    FOREIGN KEY (`client_id`)
    REFERENCES `returns`.`user_client` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `returns`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`client` ;

CREATE TABLE IF NOT EXISTS `returns`.`client` (
  `client_id` INT NOT NULL AUTO_INCREMENT,
  `client_name` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `phone` VARCHAR(45) NULL,
  `created_date` DATETIME NULL,
  `meta` TEXT NULL,
  PRIMARY KEY (`client_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `returns`.`bulk_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`bulk_category` ;

CREATE TABLE IF NOT EXISTS `returns`.`bulk_category` (
  `bulk_category_id` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(255) NULL,
  `created_date` DATETIME NULL,
  PRIMARY KEY (`bulk_category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `returns`.`bulk_lot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`bulk_lot` ;

CREATE TABLE IF NOT EXISTS `returns`.`bulk_lot` (
  `bulk_lot_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `short_desc` VARCHAR(255) NULL,
  `long_desc` TEXT NULL,
  `has_item_info` TINYINT NULL,
  `qty` INT NULL,
  `expected_min_qty` INT NULL,
  `expected_max_qty` INT NULL,
  `type` INT NOT NULL DEFAULT 1 COMMENT '1 = bid, 2 = Buy',
  `is_exclusive` TINYINT NULL,
  `created_date` DATETIME NULL,
  `updated_date` DATETIME NULL,
  `client_client_id` INT NOT NULL,
  `meta` TEXT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`bulk_lot_id`, `client_client_id`, `category_id`),
  INDEX `fk_lot_client1_idx` (`client_client_id` ASC),
  INDEX `fk_bulk_lot_category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_lot_client1`
    FOREIGN KEY (`client_client_id`)
    REFERENCES `returns`.`client` (`client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bulk_lot_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `returns`.`bulk_category` (`bulk_category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `returns`.`bulk_lot_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`bulk_lot_items` ;

CREATE TABLE IF NOT EXISTS `returns`.`bulk_lot_items` (
  `bulk_lot_item_id` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(255) NOT NULL,
  `catalog_id` INT NULL,
  `model` VARCHAR(255) NULL,
  `retail_price` FLOAT NULL,
  `category` VARCHAR(255) NULL,
  `brand` VARCHAR(255) NULL,
  `created_date` DATETIME NULL,
  `updated_date` DATETIME NULL,
  `bulk_lot_id` INT NOT NULL,
  `lot_details_id` INT NULL COMMENT 'Nullable \nFK mapping to lot details',
  `cpu_id` INT NULL COMMENT 'Nullable\nFK relationship with client_product_upload table',
  PRIMARY KEY (`bulk_lot_item_id`, `bulk_lot_id`),
  INDEX `fk_lot_items_lot_idx` (`bulk_lot_id` ASC),
  CONSTRAINT `fk_lot_items_lot`
    FOREIGN KEY (`bulk_lot_id`)
    REFERENCES `returns`.`bulk_lot` (`bulk_lot_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `returns`.`user1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`user1` ;

CREATE TABLE IF NOT EXISTS `returns`.`user1` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `first_name` VARCHAR(100) NULL,
  `last_name` VARCHAR(100) NULL,
  `created_date` DATETIME NULL,
  `meta` TEXT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `returns`.`bid_campaign`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`bid_campaign` ;

CREATE TABLE IF NOT EXISTS `returns`.`bid_campaign` (
  `bp_id` INT NOT NULL AUTO_INCREMENT,
  `min_opening_bid` FLOAT NULL,
  `earnest_money_required` BIT NULL,
  `earnest_money_amount` FLOAT NULL,
  `increment_type` TINYINT NULL COMMENT '1 = Percent\n2 = Value',
  `increment_value` FLOAT NULL,
  `reserve_amount` FLOAT NULL,
  `current_bid` FLOAT NULL,
  `current_bid_time` DATETIME NULL,
  `bulk_lot_id` INT NOT NULL,
  `current_bid_user_id` INT NOT NULL,
  PRIMARY KEY (`bp_id`, `bulk_lot_id`, `current_bid_user_id`),
  INDEX `fk_bid_price_lot1_idx` (`bulk_lot_id` ASC),
  INDEX `fk_bid_price_user1_idx` (`current_bid_user_id` ASC),
  CONSTRAINT `fk_bid_price_lot1`
    FOREIGN KEY (`bulk_lot_id`)
    REFERENCES `returns`.`bulk_lot` (`bulk_lot_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bid_price_user1`
    FOREIGN KEY (`current_bid_user_id`)
    REFERENCES `returns`.`user1` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `returns`.`bid_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`bid_history` ;

CREATE TABLE IF NOT EXISTS `returns`.`bid_history` (
  `history_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `old_bid_amount` FLOAT NULL,
  `new_bid_amount` FLOAT NULL,
  `created_date` DATETIME NULL,
  `bp_id` INT NOT NULL,
  `bulk_lot_id` INT NOT NULL,
  PRIMARY KEY (`history_id`, `user_id`, `bp_id`, `bulk_lot_id`),
  INDEX `fk_bid_history_user1_idx` (`user_id` ASC),
  INDEX `fk_bid_history_bid_price1_idx` (`bp_id` ASC, `bulk_lot_id` ASC),
  CONSTRAINT `fk_bid_history_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `returns`.`user1` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bid_history_bid_price1`
    FOREIGN KEY (`bp_id` , `bulk_lot_id`)
    REFERENCES `returns`.`bid_campaign` (`bp_id` , `bulk_lot_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `returns`.`bid_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`bid_status` ;

CREATE TABLE IF NOT EXISTS `returns`.`bid_status` (
  `bs_id` INT NOT NULL AUTO_INCREMENT,
  `bid_start_time` DATETIME NULL,
  `bid_end_time` DATETIME NULL COMMENT '	',
  `status` TINYINT NULL,
  `bp_id` INT NOT NULL,
  `bulk_lot_id` INT NOT NULL,
  PRIMARY KEY (`bs_id`, `bp_id`, `bulk_lot_id`),
  INDEX `fk_bid_status_bid_price1_idx` (`bp_id` ASC, `bulk_lot_id` ASC),
  CONSTRAINT `fk_bid_status_bid_price1`
    FOREIGN KEY (`bp_id` , `bulk_lot_id`)
    REFERENCES `returns`.`bid_campaign` (`bp_id` , `bulk_lot_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `returns`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`payment` ;

CREATE TABLE IF NOT EXISTS `returns`.`payment` (
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `payment_mode` TINYINT NULL COMMENT '1 = payment link\n2 = cheque\n3 = credit card\n4 = bank transfer\n5  = draft\n6 = cash',
  `payment_link` VARCHAR(255) NULL,
  `payment_gateway` VARCHAR(100) NULL,
  `bank_transaction_id` VARCHAR(100) NULL,
  `cheque_details` TEXT NULL COMMENT 'json',
  `credit_card_swipe_details` TEXT NULL COMMENT 'json\n',
  `created_date` DATETIME NULL,
  `meta` TEXT NULL,
  PRIMARY KEY (`payment_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `returns`.`bid_confirmation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`bid_confirmation` ;

CREATE TABLE IF NOT EXISTS `returns`.`bid_confirmation` (
  `confirmation_id` INT NOT NULL AUTO_INCREMENT,
  `history_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `bulk_lot_id` INT NOT NULL,
  `bid_amount` FLOAT NULL,
  `created_date` DATETIME NULL,
  `payment_id` INT NOT NULL,
  PRIMARY KEY (`confirmation_id`, `history_id`, `user_id`, `bulk_lot_id`, `payment_id`),
  INDEX `fk_bid_confirmation_payment1_idx` (`payment_id` ASC),
  CONSTRAINT `fk_bid_confirmation_bid_history1`
    FOREIGN KEY (`history_id` , `user_id` , `bulk_lot_id`)
    REFERENCES `returns`.`bid_history` (`history_id` , `user_id` , `bulk_lot_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bid_confirmation_payment1`
    FOREIGN KEY (`payment_id`)
    REFERENCES `returns`.`payment` (`payment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `returns`.`lot_media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`lot_media` ;

CREATE TABLE IF NOT EXISTS `returns`.`lot_media` (
  `media_id` INT NOT NULL AUTO_INCREMENT,
  `bulk_lot_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  PRIMARY KEY (`media_id`, `bulk_lot_id`, `client_id`),
  INDEX `fk_lot_media_lot1_idx` (`bulk_lot_id` ASC, `client_id` ASC),
  CONSTRAINT `fk_lot_media_lot1`
    FOREIGN KEY (`bulk_lot_id` , `client_id`)
    REFERENCES `returns`.`bulk_lot` (`bulk_lot_id` , `client_client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `returns`.`triggers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`triggers` ;

CREATE TABLE IF NOT EXISTS `returns`.`triggers` (
  `trigger_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `created_date` DATETIME NULL,
  PRIMARY KEY (`trigger_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `returns`.`notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`notification` ;

CREATE TABLE IF NOT EXISTS `returns`.`notification` (
  `notification_id` INT NOT NULL AUTO_INCREMENT,
  `notification_type` TINYINT NULL COMMENT '1 = email\n2 = sms\n3 = push notification',
  `description` TEXT NULL,
  `status` TINYINT NULL COMMENT '0 = disable\n1 = enable\n',
  `created_date` DATETIME NULL,
  `trigger_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  PRIMARY KEY (`notification_id`, `trigger_id`, `client_id`),
  INDEX `fk_notification_triggers1_idx` (`trigger_id` ASC),
  INDEX `fk_notification_client1_idx` (`client_id` ASC),
  CONSTRAINT `fk_notification_triggers1`
    FOREIGN KEY (`trigger_id`)
    REFERENCES `returns`.`triggers` (`trigger_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notification_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `returns`.`client` (`client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `returns`.`notification_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`notification_history` ;

CREATE TABLE IF NOT EXISTS `returns`.`notification_history` (
  `notification_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `created_date` DATETIME NULL,
  `sent` BIT NULL,
  PRIMARY KEY (`notification_id`, `user_id`),
  INDEX `fk_notification_history_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_notification_history_notification1`
    FOREIGN KEY (`notification_id`)
    REFERENCES `returns`.`notification` (`notification_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notification_history_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `returns`.`user1` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `returns`.`services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`services` ;

CREATE TABLE IF NOT EXISTS `returns`.`services` (
  `service_id` INT NOT NULL,
  `service_name` VARCHAR(255) NOT NULL,
  `short_desc` VARCHAR(255) NULL,
  `long_desc` TEXT NULL,
  `has_exclusivity` TINYINT NOT NULL,
  `created_date` DATETIME NOT NULL,
  `updated_date` DATETIME NULL,
  PRIMARY KEY (`service_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `returns`.`service_client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `returns`.`service_client` ;

CREATE TABLE IF NOT EXISTS `returns`.`service_client` (
  `service_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  PRIMARY KEY (`service_id`),
  CONSTRAINT `fk_service_client_services1`
    FOREIGN KEY (`service_id`)
    REFERENCES `returns`.`services` (`service_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
